### ISSUE TITLE
a "add this recipes to this date" button at the end of each recipe

### ISSUE THREAD

**Issue by bebechat** [jessebutterfield/recipes#37]
maybe a scroll down menu. when browsing throuh the recipes, it could be nice not to have to exit the recipe, go to the date to add the recipe to that date

**Comment by jessebutterfield** [comment]
So I added this functionality and I added the ability to search through recipes. It works way better on chrome than it does on Safari as Safari has fallen behind on html5. @bebechat are you using chrome now? Can you try it out and tell me if it works for you. I think on Safari you'd have to type the date like 2016-10-16

**Comment by bebechat** [comment]
Thanks!
I am using firefox and safari. I've tried on both and I entered it as " 2016-10-18", and it worked.
As of the search button, it is very nice since the recipes are not categorized!

**Comment by jessebutterfield** [comment]
Ok, so I changed this so that the calendar input will work on firefox and safari as well now. I think it works fairly well, so I'm going to call this feature done.
