### ISSUE TITLE
automatically place the cursor

### ISSUE THREAD

**Issue by bebechat** [jessebutterfield/recipes#38]
when adding an ingredient, automatically place the cursor in the very left box, already ready to type

**Comment by jessebutterfield** [comment]
This is done for the edit recipe page now. I haven't added it for the edit day page yet.

**Comment by jessebutterfield** [comment]
This is now done and deployed for both pages.

**Comment by bebechat** [comment]
I'll try it out during nap time!

**Comment by bebechat** [comment]
Thanks!
